using System.IO;
using System.Reflection;

namespace Ical.Net.CoreUnitTests
{
    internal class IcsFiles
    {
        static readonly Assembly _assembly = typeof(IcsFiles).GetTypeInfo().Assembly;

        internal static string ReadStream(string manifestResource)
        {
            using (var stream = new FileStream(manifestResource, FileMode.Open))
            {
                return new StreamReader(stream).ReadToEnd();
            }
        }

        internal static string Alarm1 => ReadStream("Calendars/Alarm/ALARM1.ics");
        internal static string Alarm2 => ReadStream("Calendars/Alarm/ALARM2.ics");
        internal static string Alarm3 => ReadStream("Calendars/Alarm/ALARM3.ics");
        internal static string Alarm4 => ReadStream("Calendars/Alarm/ALARM4.ics");
        internal static string Alarm5 => ReadStream("Calendars/Alarm/ALARM5.ics");
        internal static string Alarm6 => ReadStream("Calendars/Alarm/ALARM6.ics");
        internal static string Alarm7 => ReadStream("Calendars/Alarm/ALARM7.ics");
        internal static string Attachment3 => ReadStream("Calendars/Serialization/Attachment3.ics");
        internal static string Attachment4 => ReadStream("Calendars/Serialization/Attachment4.ics");
        internal static string Attendee1 => ReadStream("Calendars/Serialization/Attendee1.ics");
        internal static string Attendee2 => ReadStream("Calendars/Serialization/Attendee2.ics");
        internal static string Bug1741093 => ReadStream("Calendars/Recurrence/Bug1741093.ics");
        internal static string Bug2033495 => ReadStream("Calendars/Serialization/Bug2033495.ics");
        internal static string Bug2148092 => ReadStream("Calendars/Serialization/Bug2148092.ics");
        internal static string Bug2912657 => ReadStream("Calendars/Recurrence/Bug2912657.ics");
        internal static string Bug2916581 => ReadStream("Calendars/Recurrence/Bug2916581.ics");
        internal static string Bug2938007 => ReadStream("Calendars/Serialization/Bug2938007.ics");
        internal static string Bug2959692 => ReadStream("Calendars/Recurrence/Bug2959692.ics");
        internal static string Bug2966236 => ReadStream("Calendars/Recurrence/Bug2966236.ics");
        internal static string Bug3007244 => ReadStream("Calendars/Recurrence/Bug3007244.ics");
        internal static string ByMonth1 => ReadStream("Calendars/Recurrence/ByMonth1.ics");
        internal static string ByMonth2 => ReadStream("Calendars/Recurrence/ByMonth2.ics");
        internal static string ByMonthDay1 => ReadStream("Calendars/Recurrence/ByMonthDay1.ics");
        internal static string Calendar1 => ReadStream("Calendars/Serialization/Calendar1.ics");
        internal static string CalendarParameters2 => ReadStream("Calendars/Serialization/CalendarParameters2.ics");
        internal static string CaseInsensitive1 => ReadStream("Calendars/Serialization/CaseInsensitive1.ics");
        internal static string CaseInsensitive2 => ReadStream("Calendars/Serialization/CaseInsensitive2.ics");
        internal static string CaseInsensitive3 => ReadStream("Calendars/Serialization/CaseInsensitive3.ics");
        internal static string CaseInsensitive4 => ReadStream("Calendars/Serialization/CaseInsensitive4.ics");
        internal static string Categories1 => ReadStream("Calendars/Serialization/Categories1.ics");
        internal static string Daily1 => ReadStream("Calendars/Recurrence/Daily1.ics");
        internal static string DailyByDay1 => ReadStream("Calendars/Recurrence/DailyByDay1.ics");
        internal static string DailyByHourMinute1 => ReadStream("Calendars/Recurrence/DailyByHourMinute1.ics");
        internal static string DailyCount1 => ReadStream("Calendars/Recurrence/DailyCount1.ics");
        internal static string DailyCount2 => ReadStream("Calendars/Recurrence/DailyCount2.ics");
        internal static string DailyInterval1 => ReadStream("Calendars/Recurrence/DailyInterval1.ics");
        internal static string DailyInterval2 => ReadStream("Calendars/Recurrence/DailyInterval2.ics");
        internal static string DailyUntil1 => ReadStream("Calendars/Recurrence/DailyUntil1.ics");
        internal static string DateTime1 => ReadStream("Calendars/Serialization/DateTime1.ics");
        internal static string DateTime2 => ReadStream("Calendars/Serialization/DateTime2.ics");
        internal static string Duration1 => ReadStream("Calendars/Serialization/Duration1.ics");
        internal static string Empty1 => ReadStream("Calendars/Recurrence/Empty1.ics");
        internal static string EmptyLines1 => ReadStream("Calendars/Serialization/EmptyLines1.ics");
        internal static string EmptyLines2 => ReadStream("Calendars/Serialization/EmptyLines2.ics");
        internal static string EmptyLines3 => ReadStream("Calendars/Serialization/EmptyLines3.ics");
        internal static string EmptyLines4 => ReadStream("Calendars/Serialization/EmptyLines4.ics");
        internal static string Encoding1 => ReadStream("Calendars/Serialization/Encoding1.ics");
        internal static string Encoding2 => ReadStream("Calendars/Serialization/Encoding2.ics");
        internal static string Encoding3 => ReadStream("Calendars/Serialization/Encoding3.ics");
        internal static string Event1 => ReadStream("Calendars/Serialization/Event1.ics");
        internal static string Event2 => ReadStream("Calendars/Serialization/Event2.ics");
        internal static string Event3 => ReadStream("Calendars/Serialization/Event3.ics");
        internal static string Event4 => ReadStream("Calendars/Serialization/Event4.ics");
        internal static string EventStatus => ReadStream("Calendars/Serialization/EventStatus.ics");
        internal static string GeographicLocation1 => ReadStream("Calendars/Serialization/GeographicLocation1.ics");
        internal static string Google1 => ReadStream("Calendars/Serialization/Google1.ics");
        internal static string Hourly1 => ReadStream("Calendars/Recurrence/Hourly1.ics");
        internal static string HourlyInterval1 => ReadStream("Calendars/Recurrence/HourlyInterval1.ics");
        internal static string HourlyInterval2 => ReadStream("Calendars/Recurrence/HourlyInterval2.ics");
        internal static string HourlyUntil1 => ReadStream("Calendars/Recurrence/HourlyUntil1.ics");
        internal static string Journal1 => ReadStream("Calendars/Journal/JOURNAL1.ics");
        internal static string Journal2 => ReadStream("Calendars/Journal/JOURNAL2.ics");
        internal static string Language1 => ReadStream("Calendars/Serialization/Language1.ics");
        internal static string Language2 => ReadStream("Calendars/Serialization/Language2.ics");
        internal static string Language3 => ReadStream("Calendars/Serialization/Language3.ics");
        internal static string Language4 => ReadStream("Calendars/Serialization/Language4.ics");
        internal static string Minutely1 => ReadStream("Calendars/Recurrence/Minutely1.ics");
        internal static string MinutelyByHour1 => ReadStream("Calendars/Recurrence/MinutelyByHour1.ics");
        internal static string MinutelyCount1 => ReadStream("Calendars/Recurrence/MinutelyCount1.ics");
        internal static string MinutelyCount2 => ReadStream("Calendars/Recurrence/MinutelyCount2.ics");
        internal static string MinutelyCount3 => ReadStream("Calendars/Recurrence/MinutelyCount3.ics");
        internal static string MinutelyCount4 => ReadStream("Calendars/Recurrence/MinutelyCount4.ics");
        internal static string MinutelyInterval1 => ReadStream("Calendars/Recurrence/MinutelyInterval1.ics");
        internal static string Monthly1 => ReadStream("Calendars/Recurrence/Monthly1.ics");
        internal static string MonthlyByDay1 => ReadStream("Calendars/Recurrence/MonthlyByDay1.ics");
        internal static string MonthlyByMonthDay1 => ReadStream("Calendars/Recurrence/MonthlyByMonthDay1.ics");
        internal static string MonthlyByMonthDay2 => ReadStream("Calendars/Recurrence/MonthlyByMonthDay2.ics");
        internal static string MonthlyBySetPos1 => ReadStream("Calendars/Recurrence/MonthlyBySetPos1.ics");
        internal static string MonthlyBySetPos2 => ReadStream("Calendars/Recurrence/MonthlyBySetPos2.ics");
        internal static string MonthlyCountByDay1 => ReadStream("Calendars/Recurrence/MonthlyCountByDay1.ics");
        internal static string MonthlyCountByDay2 => ReadStream("Calendars/Recurrence/MonthlyCountByDay2.ics");
        internal static string MonthlyCountByDay3 => ReadStream("Calendars/Recurrence/MonthlyCountByDay3.ics");
        internal static string MonthlyCountByMonthDay1 => ReadStream("Calendars/Recurrence/MonthlyCountByMonthDay1.ics");
        internal static string MonthlyCountByMonthDay2 => ReadStream("Calendars/Recurrence/MonthlyCountByMonthDay2.ics");
        internal static string MonthlyCountByMonthDay3 => ReadStream("Calendars/Recurrence/MonthlyCountByMonthDay3.ics");
        internal static string MonthlyInterval1 => ReadStream("Calendars/Recurrence/MonthlyInterval1.ics");
        internal static string MonthlyUntilByDay1 => ReadStream("Calendars/Recurrence/MonthlyUntilByDay1.ics");
        internal static string Outlook2007LineFolds => ReadStream("Calendars/Serialization/Outlook2007LineFolds.ics");
        internal static string Parameter1 => ReadStream("Calendars/Serialization/Parameter1.ics");
        internal static string Parameter2 => ReadStream("Calendars/Serialization/Parameter2.ics");
        internal static string Parse1 => ReadStream("Calendars/Serialization/Parse1.ics");
        internal static string Parse17 => ReadStream("Calendars/Serialization/PARSE17.ics");
        internal static string ProdId1 => ReadStream("Calendars/Serialization/ProdID1.ics");
        internal static string ProdId2 => ReadStream("Calendars/Serialization/ProdID2.ics");
        internal static string Property1 => ReadStream("Calendars/Serialization/Property1.ics");
        internal static string RecurrenceDates1 => ReadStream("Calendars/Serialization/RecurrenceDates1.ics");
        internal static string RequestStatus1 => ReadStream("Calendars/Serialization/RequestStatus1.ics");
        internal static string Secondly1 => ReadStream("Calendars/Recurrence/Secondly1.ics");
        internal static string TimeZone1 => ReadStream("Calendars/Serialization/TimeZone1.ics");
        internal static string TimeZone2 => ReadStream("Calendars/Serialization/TimeZone2.ics");
        internal static string TimeZone3 => ReadStream("Calendars/Serialization/TimeZone3.ics");
        internal static string Todo1 => ReadStream("Calendars/Todo/Todo1.ics");
        internal static string Todo2 => ReadStream("Calendars/Todo/Todo2.ics");
        internal static string Todo3 => ReadStream("Calendars/Todo/Todo3.ics");
        internal static string Todo4 => ReadStream("Calendars/Todo/Todo4.ics");
        internal static string Todo5 => ReadStream("Calendars/Todo/Todo5.ics");
        internal static string Todo6 => ReadStream("Calendars/Todo/Todo6.ics");
        internal static string Todo7 => ReadStream("Calendars/Todo/Todo7.ics");
        internal static string Todo8 => ReadStream("Calendars/Todo/Todo8.ics");
        internal static string Todo9 => ReadStream("Calendars/Todo/Todo9.ics");
        internal static string Transparency1 => ReadStream("Calendars/Serialization/Transparency1.ics");
        internal static string Transparency2 => ReadStream("Calendars/Serialization/Transparency2.ics");
        internal static string Trigger1 => ReadStream("Calendars/Serialization/Trigger1.ics");
        internal static string UsHolidays => ReadStream("Calendars/Serialization/USHolidays.ics");
        internal static string WeeklyCount1 => ReadStream("Calendars/Recurrence/WeeklyCount1.ics");
        internal static string WeeklyCountWkst1 => ReadStream("Calendars/Recurrence/WeeklyCountWkst1.ics");
        internal static string WeeklyCountWkst2 => ReadStream("Calendars/Recurrence/WeeklyCountWkst2.ics");
        internal static string WeeklyCountWkst3 => ReadStream("Calendars/Recurrence/WeeklyCountWkst3.ics");
        internal static string WeeklyCountWkst4 => ReadStream("Calendars/Recurrence/WeeklyCountWkst4.ics");
        internal static string WeeklyInterval1 => ReadStream("Calendars/Recurrence/WeeklyInterval1.ics");
        internal static string WeeklyUntil1 => ReadStream("Calendars/Recurrence/WeeklyUntil1.ics");
        internal static string WeeklyUntilWkst1 => ReadStream("Calendars/Recurrence/WeeklyUntilWkst1.ics");
        internal static string WeeklyUntilWkst2 => ReadStream("Calendars/Recurrence/WeeklyUntilWkst2.ics");
        internal static string WeeklyWeekStartsLastYear => ReadStream("Calendars/Recurrence/WeeklyWeekStartsLastYear.ics");
        internal static string WeeklyWkst1 => ReadStream("Calendars/Recurrence/WeeklyWkst1.ics");
        internal static string XProperty1 => ReadStream("Calendars/Serialization/XProperty1.ics");
        internal static string XProperty2 => ReadStream("Calendars/Serialization/XProperty2.ics");
        internal static string Yearly1 => ReadStream("Calendars/Recurrence/Yearly1.ics");
        internal static string YearlyByDay1 => ReadStream("Calendars/Recurrence/YearlyByDay1.ics");
        internal static string YearlyByMonth1 => ReadStream("Calendars/Recurrence/YearlyByMonth1.ics");
        internal static string YearlyByMonth2 => ReadStream("Calendars/Recurrence/YearlyByMonth2.ics");
        internal static string YearlyByMonth3 => ReadStream("Calendars/Recurrence/YearlyByMonth3.ics");
        internal static string YearlyByMonthDay1 => ReadStream("Calendars/Recurrence/YearlyByMonthDay1.ics");
        internal static string YearlyBySetPos1 => ReadStream("Calendars/Recurrence/YearlyBySetPos1.ics");
        internal static string YearlyByWeekNo1 => ReadStream("Calendars/Recurrence/YearlyByWeekNo1.ics");
        internal static string YearlyByWeekNo2 => ReadStream("Calendars/Recurrence/YearlyByWeekNo2.ics");
        internal static string YearlyByWeekNo3 => ReadStream("Calendars/Recurrence/YearlyByWeekNo3.ics");
        internal static string YearlyByWeekNo4 => ReadStream("Calendars/Recurrence/YearlyByWeekNo4.ics");
        internal static string YearlyByWeekNo5 => ReadStream("Calendars/Recurrence/YearlyByWeekNo5.ics");
        internal static string YearlyComplex1 => ReadStream("Calendars/Recurrence/YearlyComplex1.ics");
        internal static string YearlyCountByMonth1 => ReadStream("Calendars/Recurrence/YearlyCountByMonth1.ics");
        internal static string YearlyCountByYearDay1 => ReadStream("Calendars/Recurrence/YearlyCountByYearDay1.ics");
        internal static string YearlyInterval1 => ReadStream("Calendars/Recurrence/YearlyInterval1.ics");
    }
}
