//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDay.iCal.Validator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDay.iCal.Validator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calendar is either not loaded or is unavailable..
        /// </summary>
        internal static string CalendarNotLoadedError {
            get {
                return ResourceManager.GetString("CalendarNotLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure a proper network connection if accessing the calendar over the network..
        /// </summary>
        internal static string CalendarNotLoadedError_Resolution1 {
            get {
                return ResourceManager.GetString("CalendarNotLoadedError_Resolution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure a firewall is not blocking access to the calendar..
        /// </summary>
        internal static string CalendarNotLoadedError_Resolution2 {
            get {
                return ResourceManager.GetString("CalendarNotLoadedError_Resolution2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calendar failed to parse for the following reason:.
        /// </summary>
        internal static string CalendarParseError {
            get {
                return ResourceManager.GetString("CalendarParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ColumnString {
            get {
                return ResourceManager.GetString("ColumnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string LineString {
            get {
                return ResourceManager.GetString("LineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calendar is missing a VERSION parameter..
        /// </summary>
        internal static string MissingVersionError {
            get {
                return ResourceManager.GetString("MissingVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a VERSION parameter to the iCalendar.  See RFC 2445 section 4.7.4 for details..
        /// </summary>
        internal static string MissingVersionError_Resolution1 {
            get {
                return ResourceManager.GetString("MissingVersionError_Resolution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
    }
}
